/*
 * Enumerated Values Table 
 */

/*Create Generic String Values*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(0, 0, 'ROOT', 0);

/*Language Tree Root*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(1, 0, 'Language Tree', 0);

/*Langage Families*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(2, 1, 'Germanic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(3, 1, 'Romance', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(4, 1, 'Celtic', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(5, 1, 'Greek', 3);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(6, 1, 'Balto-Slavic', 4);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(7, 1, 'Albanian', 5);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(8, 1, 'Armenian', 6);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(9, 1, 'Indo-Iranian', 7);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(10, 1, 'Caucasian', 8);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(11, 1, 'Sino-Tibetan', 9);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(12, 1, 'Semito-Hamitic', 10);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(13, 1, 'Dravidian', 11);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(14, 1, 'Japanese', 12);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(15, 1, 'Altaic', 13);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(16, 1, 'Vietnamese', 14);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(17, 1, 'Mon-Khmer', 15);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(18, 1, 'Korean', 16);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(19, 1, 'Bantu', 17);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(20, 1, 'Malayo-Polynesian', 18);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(21, 1, 'Armerindian', 19);

/*Language Groups*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(22, 2, 'Anglic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(23, 2, 'West Germanic', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(24, 2, 'North Germanic', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(25, 3, 'East Romance', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(26, 3, 'West Romance', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(27, 3, 'E&W Romance', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(28, 4, 'Goidelic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(29, 4, 'Brythonic', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(30, 5, 'Greek', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(31, 6, 'Baltic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(32, 6, 'East Slavic', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(33, 6, 'West Slavic', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(34, 6, 'South Slavic', 3);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(35, 7, 'Albanian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(36, 8, 'Armenian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(37, 9, 'Indic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(38, 9, 'Iranian', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(39, 10, 'South Caucasian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(40, 11, 'Sinitic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(41, 11, 'Tibeto-Burman', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(42, 12, 'Semitic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(43, 12, 'Hamitic', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(44, 13, 'Dravidian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(45, 14, 'Japanese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(46, 15, 'Turkic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(47, 15, 'Ugric', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(48, 15, 'Finnic', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(49, 16, 'Vietnamese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(50, 17, 'Mon-Khemer', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(51, 18, 'Korean', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(52, 19, 'Bantu', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(53, 20, 'W. Malayo-Polynesian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(54, 21, 'South Amerindian', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(55, 21, 'Athabascan', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(56, 21, 'Uto-Aztecan', 2);

/*Languages*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(57, 22, 'English', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(58, 23, 'German', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(59, 23, 'Dutch', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(60, 23, 'Yiddish', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(61, 23, 'Flemish', 3);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(62, 24, 'Danish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(63, 24, 'Swedish', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(64, 24, 'Norwegian', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(65, 25, 'Italian', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(66, 25, 'Romanian', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(67, 26, 'Spanish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(68, 26, 'French', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(69, 26, 'Portuguese', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(70, 27, 'Latin', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(71, 28, 'Scots Gaelic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(72, 28, 'Irish', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(73, 29, 'Welsh', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(74, 29, 'Breton', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(75, 30, 'Greek', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(76, 31, 'Lithuanian', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(77, 31, 'Latvian', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(78, 32, 'Russian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(79, 33, 'Polish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(80, 33, 'Czech', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(81, 33, 'Slovak', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(82, 34, 'Serbo-Croat', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(83, 34, 'Bulgarian', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(84, 34, 'Slovenian', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(85, 34, 'Macedonian', 3);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(86, 35, 'Albanian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(87, 36, 'Armenian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(88, 37, 'Hindi-Urdu', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(89, 37, 'Bengali', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(90, 37, 'Romany', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(91, 38, 'Taijik', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(92, 38, 'Farsi', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(93, 39, 'Georgian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(94, 40, 'Mandarin', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(95, 40, 'Cantonese', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(96, 41, 'Thai', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(97, 41, 'Burmese', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(98, 42, 'Arabic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(99, 42, 'Hebrew', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(100, 43, 'Berber', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(101, 43, 'Hausa', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(102, 44, 'Tamil', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(103, 45, 'Japanese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(104, 46, 'Turkish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(105, 46, 'Azerbaijani', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(106, 46, 'Uzbek', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(107, 46, 'Kazakh', 3);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(108, 46, 'Tartar', 4);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(109, 46, 'Chuvash', 5);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(110, 46, 'Kirzig', 6);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(111, 46, 'Turkoman', 7);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(112, 47, 'Hungarian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(113, 48, 'Finnish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(114, 48, 'Estonian', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(115, 48, 'Mordvinian', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(116, 49, 'Vietnamese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(117, 50, 'Cambodian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(118, 51, 'Korean', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(119, 52, 'Swahili', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(120, 53, 'Malay-Indonesian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(121, 54, 'Maya', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(122, 55, 'Navaho', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(123, 56, 'Nahuati', 0);

/*Gender*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(124, 0, 'Gender', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(125, 122, 'Male', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(126, 122, 'Female', 2);

/*Faction*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(127, 0, 'Faction', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(128, 127, 'NATO', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(129, 127, 'Warsaw Pact', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(130, 127, 'Neutral', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(131, 127, 'Warlord', 3);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE VALUES(132, 127, 'Other', 4);

/*
 * Other Tables 
 */

/*Attributes*/
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(0, 'Strength', 'STR');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(1, 'Agility', 'AGL');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(2, 'Constitution', 'CON');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(3, 'Intelligence', 'INT');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(4, 'Education', 'EDU');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(5, 'Charisma', 'CHR');

/*Create User Roles*/
INSERT INTO PUBLIC.T2K_ROLE VALUES (0,'newbie');
INSERT INTO PUBLIC.T2K_ROLE VALUES (1,'player');
INSERT INTO PUBLIC.T2K_ROLE VALUES (2,'creator');
INSERT INTO PUBLIC.T2K_ROLE VALUES (3,'admin');
INSERT INTO PUBLIC.T2K_ROLE VALUES (4,'superuser');
COMMIT;

/*Create Account Statuses*/
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(0,'revoked');
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(1,'suspended');
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(2,'pending');
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(3,'ok');
COMMIT;

INSERT INTO PUBLIC.T2K_INVITE (ID, EMAIL_ADDRESS, INVITE_TIMESTAMP, INVITE_TOKEN, REGISTRATION_TIMESTAMP)
	VALUES(1,'jack.bauer@arpanet.red', CURRENT_TIMESTAMP,'zigzag',NULL);
COMMIT;

CHECKPOINT;

