/*
 * Enumerated Values Table 
 */

/*Create Generic String Values*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(0, 0, 'ROOT', 0);

/*Language Tree Root*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(1, 0, 'Language Tree', 0);

/*Langage Families*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(2, 1, 'Germanic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(3, 1, 'Romance', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(4, 1, 'Celtic', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(5, 1, 'Greek', 3);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(6, 1, 'Balto-Slavic', 4);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(7, 1, 'Albanian', 5);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(8, 1, 'Armenian', 6);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(9, 1, 'Indo-Iranian', 7);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(10, 1, 'Caucasian', 8);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(11, 1, 'Sino-Tibetan', 9);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(12, 1, 'Semito-Hamitic', 10);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(13, 1, 'Dravidian', 11);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(14, 1, 'Japanese', 12);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(15, 1, 'Altaic', 13);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(16, 1, 'Vietnamese', 14);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(17, 1, 'Mon-Khmer', 15);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(18, 1, 'Korean', 16);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(19, 1, 'Bantu', 17);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(20, 1, 'Malayo-Polynesian', 18);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(21, 1, 'Armerindian', 19);

/*Language Groups*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(22, 2, 'Anglic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(23, 2, 'West Germanic', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(24, 2, 'North Germanic', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(25, 3, 'East Romance', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(26, 3, 'West Romance', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(27, 3, 'E&W Romance', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(28, 4, 'Goidelic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(29, 4, 'Brythonic', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(30, 5, 'Greek', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(31, 6, 'Baltic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(32, 6, 'East Slavic', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(33, 6, 'West Slavic', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(34, 6, 'South Slavic', 3);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(35, 7, 'Albanian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(36, 8, 'Armenian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(37, 9, 'Indic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(38, 9, 'Iranian', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(39, 10, 'South Caucasian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(40, 11, 'Sinitic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(41, 11, 'Tibeto-Burman', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(42, 12, 'Semitic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(43, 12, 'Hamitic', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(44, 13, 'Dravidian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(45, 14, 'Japanese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(46, 15, 'Turkic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(47, 15, 'Ugric', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(48, 15, 'Finnic', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(49, 16, 'Vietnamese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(50, 17, 'Mon-Khemer', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(51, 18, 'Korean', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(52, 19, 'Bantu', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(53, 20, 'W. Malayo-Polynesian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(54, 21, 'South Amerindian', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(55, 21, 'Athabascan', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(56, 21, 'Uto-Aztecan', 2);

/*Languages*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(57, 22, 'English', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(58, 23, 'German', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(59, 23, 'Dutch', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(60, 23, 'Yiddish', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(61, 23, 'Flemish', 3);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(62, 24, 'Danish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(63, 24, 'Swedish', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(64, 24, 'Norwegian', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(65, 25, 'Italian', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(66, 25, 'Romanian', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(67, 26, 'Spanish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(68, 26, 'French', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(69, 26, 'Portuguese', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(70, 27, 'Latin', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(71, 28, 'Scots Gaelic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(72, 28, 'Irish', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(73, 29, 'Welsh', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(74, 29, 'Breton', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(75, 30, 'Greek', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(76, 31, 'Lithuanian', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(77, 31, 'Latvian', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(78, 32, 'Russian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(79, 33, 'Polish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(80, 33, 'Czech', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(81, 33, 'Slovak', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(82, 34, 'Serbo-Croat', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(83, 34, 'Bulgarian', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(84, 34, 'Slovenian', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(85, 34, 'Macedonian', 3);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(86, 35, 'Albanian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(87, 36, 'Armenian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(88, 37, 'Hindi-Urdu', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(89, 37, 'Bengali', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(90, 37, 'Romany', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(91, 38, 'Taijik', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(92, 38, 'Farsi', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(93, 39, 'Georgian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(94, 40, 'Mandarin', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(95, 40, 'Cantonese', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(96, 41, 'Thai', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(97, 41, 'Burmese', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(98, 42, 'Arabic', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(99, 42, 'Hebrew', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(100, 43, 'Berber', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(101, 43, 'Hausa', 1);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(102, 44, 'Tamil', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(103, 45, 'Japanese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(104, 46, 'Turkish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(105, 46, 'Azerbaijani', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(106, 46, 'Uzbek', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(107, 46, 'Kazakh', 3);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(108, 46, 'Tartar', 4);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(109, 46, 'Chuvash', 5);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(110, 46, 'Kirzig', 6);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(111, 46, 'Turkoman', 7);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(112, 47, 'Hungarian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(113, 48, 'Finnish', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(114, 48, 'Estonian', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(115, 48, 'Mordvinian', 2);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(116, 49, 'Vietnamese', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(117, 50, 'Cambodian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(118, 51, 'Korean', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(119, 52, 'Swahili', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(120, 53, 'Malay-Indonesian', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(121, 54, 'Maya', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(122, 55, 'Navaho', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(123, 56, 'Nahuati', 0);

/*Gender*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(124, 0, 'Gender', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(125, 124, 'Male', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(126, 124, 'Female', 2);

/*Faction*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(127, 0, 'Faction', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(128, 127, 'NATO', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(129, 127, 'Warsaw Pact', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(130, 127, 'Neutral', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(131, 127, 'Warlord', 3);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(132, 127, 'Other', 4);

/*Skill Group*/
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(133, 0, 'Skill Group', 0);

INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(134, 133, 'None', 0);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(135, 133, 'Small Arms', 1);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(136, 133, 'Medical', 2);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(137, 133, 'Language', 3);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(138, 133, 'Ground Vehicle', 4);
INSERT INTO PUBLIC.T2K_ENUMERATED_VALUE (ID,VALUE_GROUP,ENUM_VALUE,ORDINAL) VALUES(139, 133, 'Pilot', 5);
COMMIT;

/*
 * Character Tables 
 */

/*Nationality*/
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(0,'American',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(1,'English',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(2,'Welsh',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(3,'Scottish',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(4,'Irish',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(5,'Anglo-Canadian',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(6,'French-Canadian',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(7,'German',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(8,'Danish',128);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(9,'Polish',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(10,'Hungarian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(11,'Czech',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(12,'Slovak',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(13,'Russian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(14,'Azerbaijani',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(15,'Ukrainian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(16,'Byelorussian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(17,'Georgian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(18,'Uzbek',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(19,'Lithuanian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(20,'Romanian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(21,'Latvian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(22,'Kazakh',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(23,'Chuvash',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(24,'Armenian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(25,'Estonian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(26,'Kirgiz',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(27,'Tartar',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(28,'Mordvinian',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(29,'Taijik',129);
INSERT INTO PUBLIC.T2K_NATIONALITY (ID,NAME,FACTION_ID) VALUES(30,'Turkoman',129);
COMMIT;

/*Army*/
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(0,'U.S.',128);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(1,'British',128);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(2,'Canadian',128);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(3,'German',128);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(4,'Danish',128);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(5,'Polish',129);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(6,'Hungarian',129);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(7,'Czech',129);
INSERT INTO PUBLIC.T2K_ARMY (ID,NAME,FACTION_ID) VALUES(8,'Soviet',129);
COMMIT;

/*Nationality-Army*/
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(0,0);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(1,1);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(1,2);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(1,3);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(1,4);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(2,5);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(2,6);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(3,7);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(4,8);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(5,9);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(6,10);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(7,11);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(7,12);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,13);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,14);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,15);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,16);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,17);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,18);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,19);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,20);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,21);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,22);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,23);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,24);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,25);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,26);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,27);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,28);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,29);
INSERT INTO PUBLIC.T2K_NATIONALITY_T2K_ARMY (ARMIES_ID,T2KNATIONALITY_ID) VALUES(8,30);
COMMIT;

/*Attributes*/
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(0, 'Strength', 'STR');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(1, 'Agility', 'AGL');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(2, 'Constitution', 'CON');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(3, 'Intelligence', 'INT');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(4, 'Education', 'EDU');
INSERT INTO PUBLIC.T2K_ATTRIBUTE VALUES(5, 'Charisma', 'CHR');
COMMIT;

/*Skills*/

/*STR*/
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(0,'Aircraft Mechanic',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(1,'Archery',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(2,'Armed Martial Arts',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(3,'Autogun',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(4,'Grenade Launcher',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(5,'Heavy Artillery',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(6,'Heavy Gun',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(7,'Mechanic',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(8,'Small Arms (Pistol)',0,1);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(9,'Small Arms (Rifle)',0,1);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(10,'Thrown Weapon',0,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(11,'Unarmed Martial Arts',0,0);

/*EDU*/
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(12,'Biology',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(13,'Chemistry',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(14,'Civil Engineer',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(15,'Computer',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(16,'Electronics',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(17,'Excavation',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(18,'Geology',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(19,'Medical (Diagnosis)',4,2);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(20,'Medical (Trauma Aid)',4,2);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(21,'Medical (Surgery)',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(22,'Metallurgy',4,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(23,'Meteorology',4,0);

/*CON*/
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(24,'Climbing',2,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(25,'Combat Engineer',2,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(26,'Parachute',2,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(27,'Riding',2,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(28,'Scuba',2,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(29,'Small Watercraft',2,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(30,'Swimming',2,0);

/*CHR*/
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(31,'Disguise',5,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(32,'Instruction',5,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(33,'Interrogation',5,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(34,'Leadership',5,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(35,'Persuasion',5,0);

/*AGL*/
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(36,'Acrobatics',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(37,'Forgery',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(38,'Ground Vehicle (Motorcycle)',1,4);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(39,'Ground Vehicle (Tracked)',1,4);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(40,'Ground Vehicle (Wheeled)',1,4);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(41,'Gunsmith',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(42,'Hovercraft',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(43,'Intrusion',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(44,'Machinist',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(45,'Pilot (Fixed-Wing)',1,5);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(46,'Pilot (Rotary-Wing)',1,5);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(47,'Snow Skiing',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(48,'Stealth',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(49,'Tac Missile',1,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(50,'Warhead',1,0);

/*INT*/
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(51,'Farming',3,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(52,'Forward Observer',3,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(53,'Navigation',3,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(54,'Observation',3,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(55,'Scrounging',3,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(56,'Survival',3,0);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID) VALUES(57,'Tracking',3,0);

/*Language Skills*/
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(58,'Language(English)',5,3,57);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(59,'Language(German)',5,3,58);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(60,'Language(Dutch)',5,3,59);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(61,'Language(Yiddish)',5,3,60);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(62,'Language(Flemish)',5,3,61);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(63,'Language(Danish)',5,3,62);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(64,'Language(Swedish)',5,3,63);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(65,'Language(Norwegian)',5,3,64);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(66,'Language(Italian)',5,3,65);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(67,'Language(Romanian)',5,3,66);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(68,'Language(Spanish)',5,3,67);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(69,'Language(French)',5,3,68);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(70,'Language(Portuguese)',5,3,69);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(71,'Language(Latin)',5,3,70);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(72,'Language(Scots Gaelic)',5,3,71);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(73,'Language(Irish)',5,3,72);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(74,'Language(Welsh)',5,3,73);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(75,'Language(Breton)',5,3,74);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(76,'Language(Greek)',5,3,75);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(77,'Language(Lithuanian)',5,3,76);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(78,'Language(Latvian)',5,3,77);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(79,'Language(Russian)',5,3,78);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(80,'Language(Polish)',5,3,79);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(81,'Language(Czech)',5,3,80);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(82,'Language(Slovak)',5,3,81);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(83,'Language(Serbo-Croat)',5,3,82);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(84,'Language(Bulgarian)',5,3,83);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(85,'Language(Slovenian)',5,3,84);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(86,'Language(Macedonian)',5,3,85);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(87,'Language(Albanian)',5,3,86);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(88,'Language(Armenian)',5,3,87);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(89,'Language(Hindi-Urdu)',5,3,88);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(90,'Language(Bengali)',5,3,89);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(91,'Language(Romany)',5,3,90);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(92,'Language(Taijik)',5,3,91);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(93,'Language(Farsi)',5,3,92);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(94,'Language(Georgian)',5,3,93);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(95,'Language(Mandarin)',5,3,94);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(96,'Language(Cantonese)',5,3,95);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(97,'Language(Thai)',5,3,96);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(98,'Language(Burmese)',5,3,97);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(99,'Language(Arabic)',5,3,98);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(100,'Language(Hebrew)',5,3,99);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(101,'Language(Berber)',5,3,100);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(102,'Language(Hausa)',5,3,101);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(103,'Language(Tamil)',5,3,102);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(104,'Language(Japanese)',5,3,103);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(105,'Language(Turkish)',5,3,104);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(106,'Language(Azerbaijani)',5,3,105);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(107,'Language(Uzbek)',5,3,106);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(108,'Language(Kazakh)',5,3,107);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(109,'Language(Tartar)',5,3,108);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(110,'Language(Chuvash)',5,3,109);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(111,'Language(Kirzig)',5,3,110);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(112,'Language(Turkoman)',5,3,111);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(113,'Language(Hungarian)',5,3,112);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(114,'Language(Finnish)',5,3,113);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(115,'Language(Estonian)',5,3,114);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(116,'Language(Mordvinian)',5,3,115);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(117,'Language(Vietnamese)',5,3,116);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(118,'Language(Cambodian)',5,3,117);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(119,'Language(Korean)',5,3,118);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(120,'Language(Swahili)',5,3,119);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(121,'Language(Malay-Indonesian)',5,3,120);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(122,'Language(Maya)',5,3,121);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(123,'Language(Navaho)',5,3,122);
INSERT INTO PUBLIC.T2K_SKILL (ID,NAME,CONTROLLINGATTRIBUTE_ID,SKILLGROUP_ID,ASSOCIATEDVALUE_ID) VALUES(124,'Language(Nahuati)',5,3,123);
COMMIT;

/*Native Laguage*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(0,20,58); /*Language(English)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(1,20,59); /*Language(German)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(2,20,60); /*Language(Dutch)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(3,20,61); /*Language(Yiddish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(4,20,62); /*Language(Flemish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(5,20,63); /*Language(Danish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(6,20,64); /*Language(Swedish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(7,20,65); /*Language(Norwegian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(8,20,66); /*Language(Italian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(9,20,67); /*Language(Romanian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(10,20,68); /*Language(Spanish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(11,20,69); /*Language(French)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(12,20,70); /*Language(Portuguese)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(13,20,71); /*Language(Latin)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(14,20,72); /*Language(Scots Gaelic)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(15,20,73); /*Language(Irish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(16,20,74); /*Language(Welsh)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(17,20,75); /*Language(Breton)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(18,20,76); /*Language(Greek)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(19,20,77); /*Language(Lithuanian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(20,20,78); /*Language(Latvian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(21,20,79); /*Language(Russian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(22,20,80); /*Language(Polish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(23,20,81); /*Language(Czech)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(24,20,82); /*Language(Slovak)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(25,20,83); /*Language(Serbo-Croat)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(26,20,84); /*Language(Bulgarian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(27,20,85); /*Language(Slovenian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(28,20,86); /*Language(Macedonian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(29,20,87); /*Language(Albanian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(30,20,88); /*Language(Armenian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(31,20,89); /*Language(Hindi-Urdu)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(32,20,90); /*Language(Bengali)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(33,20,91); /*Language(Romany)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(34,20,92); /*Language(Taijik)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(35,20,93); /*Language(Farsi)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(36,20,94); /*Language(Georgian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(37,20,95); /*Language(Mandarin)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(38,20,96); /*Language(Cantonese)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(39,20,97); /*Language(Thai)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(40,20,98); /*Language(Burmese)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(41,20,99); /*Language(Arabic)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(42,20,100); /*Language(Hebrew)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(43,20,101); /*Language(Berber)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(44,20,102); /*Language(Hausa)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(45,20,103); /*Language(Tamil)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(46,20,104); /*Language(Japanese)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(47,20,105); /*Language(Turkish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(48,20,106); /*Language(Azerbaijani)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(49,20,107); /*Language(Uzbek)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(50,20,108); /*Language(Kazakh)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(51,20,109); /*Language(Tartar)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(52,20,110); /*Language(Chuvash)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(53,20,111); /*Language(Kirzig)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(54,20,112); /*Language(Turkoman)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(55,20,113); /*Language(Hungarian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(56,20,114); /*Language(Finnish)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(57,20,115); /*Language(Estonian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(58,20,116); /*Language(Mordvinian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(59,20,117); /*Language(Vietnamese)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(60,20,118); /*Language(Cambodian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(61,20,119); /*Language(Korean)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(62,20,120); /*Language(Swahili)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(63,20,121); /*Language(Malay-Indonesian)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(64,20,122); /*Language(Maya)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(65,20,123); /*Language(Navaho)*/
INSERT INTO PUBLIC.T2K_NATIVE_LANGUAGE (ID,TARGET_NUMBER,LANGUAGESKILL_ID) VALUES(66,20,124); /*Language(Nahuati)*/
COMMIT;

/*Nationality-Native Language*/


/*
 * Account Tables 
 */

/*Create User Roles*/
INSERT INTO PUBLIC.T2K_ROLE VALUES (0,'newbie');
INSERT INTO PUBLIC.T2K_ROLE VALUES (1,'player');
INSERT INTO PUBLIC.T2K_ROLE VALUES (2,'creator');
INSERT INTO PUBLIC.T2K_ROLE VALUES (3,'admin');
INSERT INTO PUBLIC.T2K_ROLE VALUES (4,'superuser');
COMMIT;

/*Create Account Statuses*/
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(0,'revoked');
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(1,'suspended');
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(2,'pending');
INSERT INTO PUBLIC.T2K_ACCOUNT_STATUS VALUES(3,'ok');
COMMIT;

/*Initial Account*/
INSERT INTO PUBLIC.T2K_INVITE (ID, EMAIL_ADDRESS, INVITE_TIMESTAMP, INVITE_TOKEN, REGISTRATION_TIMESTAMP)
	VALUES(1,'jack.bauer@arpanet.red', CURRENT_TIMESTAMP,'zigzag',NULL);
COMMIT;

CHECKPOINT;

